In [2]:
%cd /home/magdalena/pipeline/data_preprocessing/
# Then use normal imports

from src.mining.OIDExtractor import OIDExtractor
from src.h5_constructor.CreateAstroObjectPKL import CreateAstroObjectPKL
from src.utils.end2end import create_astro_objects
from src.utils.ztf_prod_keys import ZTF_ff_columns_to_PROD
import pandas as pd

/home/magdalena/pipeline/data_preprocessing

In [4]:
to_pkl = CreateAstroObjectPKL(chunks_dir='/home/magdalena/pipeline/data_preprocessing/data/test',
                              output_dir='/home/magdalena/pipeline/data_preprocessing/data/test_pkl',
                              n_jobs=1)

['chunk_0']

Creating AstroObjects: 100%|██████████| 1/1 [00:00<00:00,  1.20chunks/s]

### AstroObject Sanity Check

#### Create the AstroObjects from the chunk extracted from the database

In [5]:
detections = pd.read_parquet('/home/magdalena/pipeline/data_preprocessing/data/test/chunk_0/detections.parquet')
fp = pd.read_parquet('/home/magdalena/pipeline/data_preprocessing/data/test/chunk_0/forced_photometry.parquet')
xmatch = pd.read_parquet('/home/magdalena/pipeline/data_preprocessing/data/test/chunk_0/xmatch.parquet')

In [6]:
astro_objects_list = create_astro_objects(detections,fp,xmatch)
print(astro_objects_list[0].features)

Empty DataFrame
Columns: [name, value, fid, sid, version]
Index: []

In [7]:
single_ao = astro_objects_list[0]

#### Extract Features and Preprocess Lightcurve for a single AstroObject

The extractors modify the data within the AstroObject.

In [11]:
 
from src.lc_classifier.lc_classifier.features.composites.ztf import ZTFFeatureExtractor
from src.lc_classifier.lc_classifier.features.preprocess.ztf import ZTFLightcurvePreprocessor

In [12]:
lc_extractor = ZTFLightcurvePreprocessor()
feature_extractor = ZTFFeatureExtractor()

In [13]:
lc_extractor.preprocess_batch([single_ao])

In [14]:
feature_extractor.compute_features_batch([single_ao])

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
/home/magdalena/pipeline/data_preprocessing/src/lc_classifier/lc_classifier/features/extractors/tde_extractor.py:176: OptimizeWarning: Covariance of the parameters could not be estimated
  parameters, _ = curve_fit(

In [15]:
display(single_ao.features)
display(single_ao.metadata)
display(single_ao.detections)

             name               value   fid  sid version
0        g-r_mean            0.308803   g,r  ZTF   1.0.0
1         g-r_max            0.338444   g,r  ZTF   1.0.0
2   g-r_mean_corr            0.670957   g,r  ZTF   1.0.0
3    g-r_max_corr            0.688856   g,r  ZTF   1.0.0
0           W1-W2  0.3390000000000004  None  ZTF   1.0.0
..            ...                 ...   ...  ...     ...
3      mean_chinr                 NaN   g,r  ZTF   1.0.0
0        Timespan           14.950532  None  ZTF   1.0.0
0    Coordinate_x             0.83071  None  ZTF   1.0.0
1    Coordinate_y            0.554099  None  ZTF   1.0.0
2    Coordinate_z             0.05381  None  ZTF   1.0.0

[203 rows x 5 columns]

        name             value
0        aid  aid_ZTF17aabqcyh
1        oid      ZTF17aabqcyh
2         W1            15.746
3         W2            15.407
4         W3            12.327
5         W4             9.214
6   sgscore1          0.010833
7     sgmag1           20.0954
8     srmag1           19.3523
9  distpsnr1          0.480968

,oid,candid,pid,ra,dec,mjd,brightness,e_brightness,fid,isdiffpos,forced,distnr,rfid,tid,sid,unit,mjd_nohelio
aid,,,,,,,,,,,,,,,,,
aid_ZTF17aabqcyh,ZTF17aabqcyh,2438433332215015011,2438433332215,33.703772,3.084593,60192.436956,18.705603,0.049527,r,1,False,0.397823,451120222.0,ZTF,ZTF,magnitude,60192.433333
aid_ZTF17aabqcyh,ZTF17aabqcyh,2441410632215015014,2441410632215,33.703912,3.084575,60195.414474,19.394459,0.103336,g,1,False,0.118881,NaN,ZTF,ZTF,magnitude,60195.410637
aid_ZTF17aabqcyh,ZTF17aabqcyh,2444387522215015011,2444387522215,33.704065,3.084562,60198.391566,19.406515,0.084280,g,1,False,0.644671,451120122.0,ZTF,ZTF,magnitude,60198.387523
aid_ZTF17aabqcyh,ZTF17aabqcyh,2447422922215015028,2447422922215,33.703987,3.084560,60201.427169,18.757057,0.043987,r,1,False,0.380188,451120222.0,ZTF,ZTF,magnitude,60201.422928
aid_ZTF17aabqcyh,ZTF17aabqcyh,2447466242215035040,2447466242215,33.704172,3.084642,60201.470493,19.474524,0.081286,g,1,False,1.068320,NaN,ZTF,ZTF,magnitude,60201.466250
aid_ZTF17aabqcyh,ZTF17aabqcyh,2451379502215015023,2451379502215,33.704116,3.084611,60205.383983,18.765060,0.060900,r,1,False,0.840866,NaN,ZTF,ZTF,magnitude,60205.379502
aid_ZTF17aabqcyh,ZTF17aabqcyh,2453382892215015021,2453382892215,33.704086,3.084631,60207.387489,18.789116,0.046070,r,1,False,0.756475,451120222.0,ZTF,ZTF,magnitude,60207.382893
aid_ZTF17aabqcyh,ZTF17aabqcyh,2438433332215015011,2438433332215,33.703772,3.084593,60192.436956,35.118633,5.456017,r,1,False,0.397823,451120222.0,ZTF,ZTF,diff_flux,60192.433333
aid_ZTF17aabqcyh,ZTF17aabqcyh,2441410632215015014,2441410632215,33.703912,3.084575,60195.414474,25.713429,6.035906,g,1,False,0.118881,NaN,ZTF,ZTF,diff_flux,60195.410637
aid_ZTF17aabqcyh,ZTF17aabqcyh,2444387522215015011,2444387522215,33.704065,3.084562,60198.391566,25.013128,4.868493,g,1,False,0.644671,451120122.0,ZTF,ZTF,diff_flux,60198.387523
aid_ZTF17aabqcyh,ZTF17aabqcyh,2447422922215015028,2447422922215,33.703987,3.084560,60201.427169,29.582631,4.621468,r,1,False,0.380188,451120222.0,ZTF,ZTF,diff_flux,60201.422928
aid_ZTF17aabqcyh,ZTF17aabqcyh,2447466242215035040,2447466242215,33.704172,3.084642,60201.470493,21.205084,4.410460,g,1,False,1.068320,NaN,ZTF,ZTF,diff_flux,60201.466250
aid_ZTF17aabqcyh,ZTF17aabqcyh,2449415002215015050,2449415002215,33.704309,3.084527,60203.419364,18.434714,3.601886,g,1,False,1.513908,451120122.0,ZTF,ZTF,diff_flux,60203.415000
aid_ZTF17aabqcyh,ZTF17aabqcyh,2451379502215015023,2451379502215,33.704116,3.084611,60205.383983,28.744847,6.351401,r,1,False,0.840866,NaN,ZTF,ZTF,diff_flux,60205.379502
aid_ZTF17aabqcyh,ZTF17aabqcyh,2453382892215015021,2453382892215,33.704086,3.084631,60207.387489,26.263657,4.699414,r,1,False,0.756475,451120222.0,ZTF,ZTF,diff_flux,60207.382893

To train the ATAT classifier the keys must be set to their production names:

In [16]:
# Load YAML config
import yaml
with open("/home/magdalena/pipeline/data_preprocessing/src/utils/config_dict/dict_info.yaml", 'r') as stream:
    config_dict = yaml.safe_load(stream)

In [17]:
display(single_ao.features)

             name               value   fid  sid version
0        g-r_mean            0.308803   g,r  ZTF   1.0.0
1         g-r_max            0.338444   g,r  ZTF   1.0.0
2   g-r_mean_corr            0.670957   g,r  ZTF   1.0.0
3    g-r_max_corr            0.688856   g,r  ZTF   1.0.0
0           W1-W2  0.3390000000000004  None  ZTF   1.0.0
..            ...                 ...   ...  ...     ...
3      mean_chinr                 NaN   g,r  ZTF   1.0.0
0        Timespan           14.950532  None  ZTF   1.0.0
0    Coordinate_x             0.83071  None  ZTF   1.0.0
1    Coordinate_y            0.554099  None  ZTF   1.0.0
2    Coordinate_z             0.05381  None  ZTF   1.0.0

[203 rows x 5 columns]

In [18]:
single_ao.features.fillna({'fid':''}, inplace=True)
single_ao.features["name_fid"] = single_ao.features['name'] + single_ao.features['fid'].apply(lambda x: '_' + x if x != '' else '')
display(single_ao.features)

             name               value  fid  sid version           name_fid
0        g-r_mean            0.308803  g,r  ZTF   1.0.0       g-r_mean_g,r
1         g-r_max            0.338444  g,r  ZTF   1.0.0        g-r_max_g,r
2   g-r_mean_corr            0.670957  g,r  ZTF   1.0.0  g-r_mean_corr_g,r
3    g-r_max_corr            0.688856  g,r  ZTF   1.0.0   g-r_max_corr_g,r
0           W1-W2  0.3390000000000004       ZTF   1.0.0              W1-W2
..            ...                 ...  ...  ...     ...                ...
3      mean_chinr                 NaN  g,r  ZTF   1.0.0     mean_chinr_g,r
0        Timespan           14.950532       ZTF   1.0.0           Timespan
0    Coordinate_x             0.83071       ZTF   1.0.0       Coordinate_x
1    Coordinate_y            0.554099       ZTF   1.0.0       Coordinate_y
2    Coordinate_z             0.05381       ZTF   1.0.0       Coordinate_z

[203 rows x 6 columns]

In [19]:

for feat in single_ao.features['name_fid']:
    print(feat)

g-r_mean_g,r
g-r_max_g,r
g-r_mean_corr_g,r
g-r_max_corr_g,r
W1-W2
W2-W3
W3-W4
g-W1
r-W1
g-W2
r-W2
g-W3
r-W3
g-W4
r-W4
sgscore1
distpsnr1
ps_g-r
ps_r-i
ps_i-z
MHPS_ratio_g
MHPS_low_g
MHPS_high_g
MHPS_non_zero_g
MHPS_PN_flag_g
MHPS_ratio_r
MHPS_low_r
MHPS_high_r
MHPS_non_zero_r
MHPS_PN_flag_r
GP_DRW_sigma_g
GP_DRW_tau_g
GP_DRW_sigma_r
GP_DRW_tau_r
Multiband_period_g,r
PPE_g,r
Period_band_g
delta_period_g
Period_band_r
delta_period_r
Power_rate_1_4_g,r
Power_rate_1_3_g,r
Power_rate_1_2_g,r
Power_rate_2_g,r
Power_rate_3_g,r
Power_rate_4_g,r
Psi_CS_g
Psi_eta_g
Psi_CS_r
Psi_eta_r
Harmonics_mse_g
Harmonics_chi_g
Harmonics_mag_1_g
Harmonics_mag_2_g
Harmonics_phase_2_g
Harmonics_mag_3_g
Harmonics_phase_3_g
Harmonics_mag_4_g
Harmonics_phase_4_g
Harmonics_mag_5_g
Harmonics_phase_5_g
Harmonics_mag_6_g
Harmonics_phase_6_g
Harmonics_mag_7_g
Harmonics_phase_7_g
Harmonics_mse_r
Harmonics_chi_r
Harmonics_mag_1_r
Harmonics_mag_2_r
Harmonics_phase_2_r
Harmonics_mag_3_r
Harmonics_phase_3_r
Harmonics_mag_4_r
Harmonics_phase_4_r
Harmonics_mag_5_r
Harmonics_phase_5_r
Harmonics_mag_6_r
Harmonics_phase_6_r
Harmonics_mag_7_r
Harmonics_phase_7_r
Amplitude_g
AndersonDarling_g
Autocor_length_g
Beyond1Std_g
Con_g
Eta_e_g
Gskew_g
MaxSlope_g
Mean_g
Meanvariance_g
MedianAbsDev_g
MedianBRP_g
PairSlopeTrend_g
PercentAmplitude_g
Q31_g
Rcs_g
Skew_g
SmallKurtosis_g
Std_g
StetsonK_g
Pvar_g
ExcessVar_g
SF_ML_amplitude_g
SF_ML_gamma_g
IAR_phi_g
LinearTrend_g
Amplitude_r
AndersonDarling_r
Autocor_length_r
Beyond1Std_r
Con_r
Eta_e_r
Gskew_r
MaxSlope_r
Mean_r
Meanvariance_r
MedianAbsDev_r
MedianBRP_r
PairSlopeTrend_r
PercentAmplitude_r
Q31_r
Rcs_r
Skew_r
SmallKurtosis_r
Std_r
StetsonK_r
Pvar_r
ExcessVar_r
SF_ML_amplitude_r
SF_ML_gamma_r
IAR_phi_r
LinearTrend_r
SPM_A_g
SPM_t0_g
SPM_gamma_g
SPM_beta_g
SPM_tau_rise_g
SPM_tau_fall_g
SPM_A_r
SPM_t0_r
SPM_gamma_r
SPM_beta_r
SPM_tau_rise_r
SPM_tau_fall_r
SPM_chi_g
SPM_chi_r
TDE_decay_g
TDE_decay_chi_g
TDE_mag0_g
TDE_decay_r
TDE_decay_chi_r
TDE_mag0_r
fleet_a_g
fleet_w_g
fleet_chi_g
fleet_m0_g
fleet_t0_g
fleet_a_r
fleet_w_r
fleet_chi_r
fleet_m0_r
fleet_t0_r
color_variation_g,r
positive_fraction_g
n_forced_phot_band_before_g
dbrightness_first_det_band_g
dbrightness_forced_phot_band_g
last_brightness_before_band_g
max_brightness_before_band_g
median_brightness_before_band_g
n_forced_phot_band_after_g
max_brightness_after_band_g
median_brightness_after_band_g
positive_fraction_r
n_forced_phot_band_before_r
dbrightness_first_det_band_r
dbrightness_forced_phot_band_r
last_brightness_before_band_r
max_brightness_before_band_r
median_brightness_before_band_r
n_forced_phot_band_after_r
max_brightness_after_band_r
median_brightness_after_band_r
ulens_u0_g
ulens_tE_g
ulens_fs_g
ulens_chi_g
ulens_t0_g
ulens_mag0_g
ulens_u0_r
ulens_tE_r
ulens_fs_r
ulens_chi_r
ulens_t0_r
ulens_mag0_r
mean_distnr_g,r
sigma_distnr_g,r
mean_sharpnr_g,r
mean_chinr_g,r
Timespan
Coordinate_x
Coordinate_y
Coordinate_z

In [20]:

for feat in single_ao.features['name']:
    print(feat)

g-r_mean
g-r_max
g-r_mean_corr
g-r_max_corr
W1-W2
W2-W3
W3-W4
g-W1
r-W1
g-W2
r-W2
g-W3
r-W3
g-W4
r-W4
sgscore1
distpsnr1
ps_g-r
ps_r-i
ps_i-z
MHPS_ratio
MHPS_low
MHPS_high
MHPS_non_zero
MHPS_PN_flag
MHPS_ratio
MHPS_low
MHPS_high
MHPS_non_zero
MHPS_PN_flag
GP_DRW_sigma
GP_DRW_tau
GP_DRW_sigma
GP_DRW_tau
Multiband_period
PPE
Period_band
delta_period
Period_band
delta_period
Power_rate_1_4
Power_rate_1_3
Power_rate_1_2
Power_rate_2
Power_rate_3
Power_rate_4
Psi_CS
Psi_eta
Psi_CS
Psi_eta
Harmonics_mse
Harmonics_chi
Harmonics_mag_1
Harmonics_mag_2
Harmonics_phase_2
Harmonics_mag_3
Harmonics_phase_3
Harmonics_mag_4
Harmonics_phase_4
Harmonics_mag_5
Harmonics_phase_5
Harmonics_mag_6
Harmonics_phase_6
Harmonics_mag_7
Harmonics_phase_7
Harmonics_mse
Harmonics_chi
Harmonics_mag_1
Harmonics_mag_2
Harmonics_phase_2
Harmonics_mag_3
Harmonics_phase_3
Harmonics_mag_4
Harmonics_phase_4
Harmonics_mag_5
Harmonics_phase_5
Harmonics_mag_6
Harmonics_phase_6
Harmonics_mag_7
Harmonics_phase_7
Amplitude
AndersonDarling
Autocor_length
Beyond1Std
Con
Eta_e
Gskew
MaxSlope
Mean
Meanvariance
MedianAbsDev
MedianBRP
PairSlopeTrend
PercentAmplitude
Q31
Rcs
Skew
SmallKurtosis
Std
StetsonK
Pvar
ExcessVar
SF_ML_amplitude
SF_ML_gamma
IAR_phi
LinearTrend
Amplitude
AndersonDarling
Autocor_length
Beyond1Std
Con
Eta_e
Gskew
MaxSlope
Mean
Meanvariance
MedianAbsDev
MedianBRP
PairSlopeTrend
PercentAmplitude
Q31
Rcs
Skew
SmallKurtosis
Std
StetsonK
Pvar
ExcessVar
SF_ML_amplitude
SF_ML_gamma
IAR_phi
LinearTrend
SPM_A
SPM_t0
SPM_gamma
SPM_beta
SPM_tau_rise
SPM_tau_fall
SPM_A
SPM_t0
SPM_gamma
SPM_beta
SPM_tau_rise
SPM_tau_fall
SPM_chi
SPM_chi
TDE_decay
TDE_decay_chi
TDE_mag0
TDE_decay
TDE_decay_chi
TDE_mag0
fleet_a
fleet_w
fleet_chi
fleet_m0
fleet_t0
fleet_a
fleet_w
fleet_chi
fleet_m0
fleet_t0
color_variation
positive_fraction
n_forced_phot_band_before
dbrightness_first_det_band
dbrightness_forced_phot_band
last_brightness_before_band
max_brightness_before_band
median_brightness_before_band
n_forced_phot_band_after
max_brightness_after_band
median_brightness_after_band
positive_fraction
n_forced_phot_band_before
dbrightness_first_det_band
dbrightness_forced_phot_band
last_brightness_before_band
max_brightness_before_band
median_brightness_before_band
n_forced_phot_band_after
max_brightness_after_band
median_brightness_after_band
ulens_u0
ulens_tE
ulens_fs
ulens_chi
ulens_t0
ulens_mag0
ulens_u0
ulens_tE
ulens_fs
ulens_chi
ulens_t0
ulens_mag0
mean_distnr
sigma_distnr
mean_sharpnr
mean_chinr
Timespan
Coordinate_x
Coordinate_y
Coordinate_z

In [21]:
single_ao.features['prod'] = single_ao.features['name_fid'].map(
    ZTF_ff_columns_to_PROD)
for feat in single_ao.features['prod']:
    print(feat)

g_r_mean_12
g_r_max_12
g_r_mean_corr_12
g_r_max_corr_12
W1_W2
W2_W3
W3_W4
g_W1
r_W1
g_W2
r_W2
g_W3
r_W3
g_W4
r_W4
sgscore1
distpsnr1
ps_g_r
nan
nan
MHPS_ratio_1
MHPS_low_1
MHPS_high_1
MHPS_non_zero_1
MHPS_PN_flag_1
MHPS_ratio_2
MHPS_low_2
MHPS_high_2
MHPS_non_zero_2
MHPS_PN_flag_2
GP_DRW_sigma_1
GP_DRW_tau_1
GP_DRW_sigma_2
GP_DRW_tau_2
Multiband_period_12
PPE_12
Period_band_1
delta_period_1
Period_band_2
delta_period_2
Power_rate_1_4_12
Power_rate_1_3_12
Power_rate_1_2_12
Power_rate_2_12
Power_rate_3_12
Power_rate_4_12
Psi_CS_1
Psi_eta_1
Psi_CS_2
Psi_eta_2
Harmonics_mse_1
Harmonics_chi_1
Harmonics_mag_1_1
Harmonics_mag_2_1
Harmonics_phase_2_1
Harmonics_mag_3_1
Harmonics_phase_3_1
Harmonics_mag_4_1
Harmonics_phase_4_1
Harmonics_mag_5_1
Harmonics_phase_5_1
Harmonics_mag_6_1
Harmonics_phase_6_1
Harmonics_mag_7_1
Harmonics_phase_7_1
Harmonics_mse_2
Harmonics_chi_2
Harmonics_mag_1_2
Harmonics_mag_2_2
Harmonics_phase_2_2
Harmonics_mag_3_2
Harmonics_phase_3_2
Harmonics_mag_4_2
Harmonics_phase_4_2
Harmonics_mag_5_2
Harmonics_phase_5_2
Harmonics_mag_6_2
Harmonics_phase_6_2
Harmonics_mag_7_2
Harmonics_phase_7_2
Amplitude_1
AndersonDarling_1
Autocor_length_1
Beyond1Std_1
Con_1
Eta_e_1
Gskew_1
MaxSlope_1
Mean_1
Meanvariance_1
MedianAbsDev_1
MedianBRP_1
PairSlopeTrend_1
PercentAmplitude_1
Q31_1
Rcs_1
Skew_1
SmallKurtosis_1
Std_1
StetsonK_1
Pvar_1
ExcessVar_1
SF_ML_amplitude_1
SF_ML_gamma_1
IAR_phi_1
LinearTrend_1
Amplitude_2
AndersonDarling_2
Autocor_length_2
Beyond1Std_2
Con_2
Eta_e_2
Gskew_2
MaxSlope_2
Mean_2
Meanvariance_2
MedianAbsDev_2
MedianBRP_2
PairSlopeTrend_2
PercentAmplitude_2
Q31_2
Rcs_2
Skew_2
SmallKurtosis_2
Std_2
StetsonK_2
Pvar_2
ExcessVar_2
SF_ML_amplitude_2
SF_ML_gamma_2
IAR_phi_2
LinearTrend_2
SPM_A_1
SPM_t0_1
SPM_gamma_1
SPM_beta_1
SPM_tau_rise_1
SPM_tau_fall_1
SPM_A_2
SPM_t0_2
SPM_gamma_2
SPM_beta_2
SPM_tau_rise_2
SPM_tau_fall_2
SPM_chi_1
SPM_chi_2
TDE_decay_1
TDE_decay_chi_1
nan
TDE_decay_2
TDE_decay_chi_2
nan
fleet_a_1
fleet_w_1
fleet_chi_1
nan
nan
fleet_a_2
fleet_w_2
fleet_chi_2
nan
nan
color_variation_12
positive_fraction_1
n_forced_phot_band_before_1
dbrightness_first_det_band_1
dbrightness_forced_phot_band_1
last_brightness_before_band_1
max_brightness_before_band_1
median_brightness_before_band_1
n_forced_phot_band_after_1
max_brightness_after_band_1
median_brightness_after_band_1
positive_fraction_2
n_forced_phot_band_before_2
dbrightness_first_det_band_2
dbrightness_forced_phot_band_2
last_brightness_before_band_2
max_brightness_before_band_2
median_brightness_before_band_2
n_forced_phot_band_after_2
max_brightness_after_band_2
median_brightness_after_band_2
ulens_u0_1
ulens_tE_1
ulens_fs_1
ulens_chi_1
nan
nan
ulens_u0_2
ulens_tE_2
ulens_fs_2
ulens_chi_2
nan
nan
nan
nan
nan
nan
Timespan
Coordinate_x
Coordinate_y
Coordinate_z

In [22]:
single_ao.features.dropna(subset=['prod'], inplace=True)
display(single_ao.features)

,name,value,fid,sid,version,name_fid,prod
0,g-r_mean,0.308803,"g,r",ZTF,1.0.0,"g-r_mean_g,r",g_r_mean_12
1,g-r_max,0.338444,"g,r",ZTF,1.0.0,"g-r_max_g,r",g_r_max_12
2,g-r_mean_corr,0.670957,"g,r",ZTF,1.0.0,"g-r_mean_corr_g,r",g_r_mean_corr_12
3,g-r_max_corr,0.688856,"g,r",ZTF,1.0.0,"g-r_max_corr_g,r",g_r_max_corr_12
0,W1-W2,0.3390000000000004,,ZTF,1.0.0,W1-W2,W1_W2
...,...,...,...,...,...,...,...
9,ulens_chi,NaN,r,ZTF,1.0.1,ulens_chi_r,ulens_chi_2
0,Timespan,14.950532,,ZTF,1.0.0,Timespan,Timespan
0,Coordinate_x,0.83071,,ZTF,1.0.0,Coordinate_x,Coordinate_x
1,Coordinate_y,0.554099,,ZTF,1.0.0,Coordinate_y,Coordinate_y
2,Coordinate_z,0.05381,,ZTF,1.0.0,Coordinate_z,Coordinate_z

In [23]:
single_ao.features = single_ao.features[single_ao.features['prod'].isin(
    config_dict["feat_cols"])]
print(config_dict['md_cols']) 
single_ao.features = single_ao.features[single_ao.features['prod'].isin(
    config_dict["md_cols"])]

['W1_W2', 'W2_W3', 'W3_W4', 'sgscore1', 'distpsnr1', 'ps_g_r']
True

(181, 6)

In [24]:
display(features)
display(metadata)

,name,value,fid,sid,version,name_fid,prod
0,g-r_mean,0.308803,"g,r",ZTF,1.0.0,"g-r_mean_g,r",g_r_mean_12
1,g-r_max,0.338444,"g,r",ZTF,1.0.0,"g-r_max_g,r",g_r_max_12
2,g-r_mean_corr,0.670957,"g,r",ZTF,1.0.0,"g-r_mean_corr_g,r",g_r_mean_corr_12
3,g-r_max_corr,0.688856,"g,r",ZTF,1.0.0,"g-r_max_corr_g,r",g_r_max_corr_12
3,g-W1,3.6791660000000004,,ZTF,1.0.0,g-W1,g_W1
...,...,...,...,...,...,...,...
9,ulens_chi,NaN,r,ZTF,1.0.1,ulens_chi_r,ulens_chi_2
0,Timespan,14.950532,,ZTF,1.0.0,Timespan,Timespan
0,Coordinate_x,0.83071,,ZTF,1.0.0,Coordinate_x,Coordinate_x
1,Coordinate_y,0.554099,,ZTF,1.0.0,Coordinate_y,Coordinate_y
2,Coordinate_z,0.05381,,ZTF,1.0.0,Coordinate_z,Coordinate_z

        name               value fid        sid version   name_fid       prod
0      W1-W2  0.3390000000000004            ZTF   1.0.0      W1-W2      W1_W2
1      W2-W3                3.08            ZTF   1.0.0      W2-W3      W2_W3
2      W3-W4  3.1129999999999995            ZTF   1.0.0      W3-W4      W3_W4
0   sgscore1                 NaN      panstarrs   1.0.1   sgscore1   sgscore1
1  distpsnr1                 NaN      panstarrs   1.0.1  distpsnr1  distpsnr1
2     ps_g-r                 NaN      panstarrs   1.0.1     ps_g-r     ps_g_r

In [29]:
len(config_dict['feat_cols']),len(config_dict['md_cols'])

(181, 6)

In [32]:
single_ao.features.shape

(187, 7)

In [30]:
import glob
import pickle
import requests
import sqlalchemy as sa
aos_paths = glob.glob('/home/magdalena/pipeline/data_preprocessing/data/test_pkl/chunk_0/*')#[3:]
with open(f'{aos_paths[0]}', 'rb') as f:
    data = pickle.load(f)

In [31]:

# Now, 'data' contains the loaded object
print(data.features.shape)
print(data.features)

# Now, 'data' contains the loaded object
print(data.metadata.shape)
print(data.metadata)

(0, 5)
Empty DataFrame
Columns: [name, value, fid, sid, version]
Index: []
(10, 2)
        name             value
0        aid  aid_ZTF23aaixaqp
1        oid      ZTF23aaixaqp
2         W1               NaN
3         W2               NaN
4         W3               NaN
5         W4               NaN
6   sgscore1          0.015938
7     sgmag1            -999.0
8     srmag1           21.3083
9  distpsnr1          2.267093